---

- name: ping
  hosts: Wordpress
  become: yes
  tasks:
    - name: ping_machine_cible
      ping:
      # PHP
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install php
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-fpm
        - php-mysql
        - php-xml
    - name: Remove apache2
      package:
        name: apache2
        state: absent

   # MySQL
    - name: Install MySQL
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python-mysqldb

    - name: Generate new root password
      command: openssl rand -hex 7
      args:
        creates: /root/.my.cnf
      register: mysql_new_root_pass
    #  when: mysql_new_root_pass.changed

    - name: Remove anonymous users
      mysql_user:
        name: ""
        state: absent
      when: mysql_new_root_pass.changed

    - name: Remove test database
      mysql_db:
        name: test
        state: absent
      when: mysql_new_root_pass.changed

    - name: Output new root password
      debug:
        msg: "New root password is {{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed

    - name: Update root password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_new_root_pass.stdout }}"
      loop:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      when: mysql_new_root_pass.changed

    - name: Create my.cnf
      template:
        src: templates/mysql/my.cnf.j2
        dest: /root/.my.cnf
      when: mysql_new_root_pass.changed

    - name: Install nginx
      package:
        name: nginx
        state: present
    - name: Start nginx
      service:
        name: nginx
        state: started
    - name: Create nginx config
      template:
        src: templates/nginx/default.j2s
        dest: /etc/nginx/sites-available/default
    #  notify: restart nginx

    - name: Check PHP version
      command: php --version
      register: php_version
    - set_fact:
        fpm_sock: /run/php/php7.{{ php_version.stdout.split(" ")[1].split(".")[1] }}-fpm.sock
      when: ansible_distribution == 'Ubuntu'

    - name: Create mysqld.cnf
      template:
        src: templates/mysql/mysqld.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      when: mysql_new_root_pass.changed
      notify: restart mysql

      # WordPress
    - name: install Unzip
      command: apt-get install unzip

    - name: Unzip WordPress
      unarchive:
        src: files/wordpress-5.3.2-fr_FR.zip
        dest: /tmp
        creates: /tmp/wordpress/wp-settings.php
    - name: Create project folder
      file:
        dest: /var/www/book.example.com
        state: directory
    - name: Copy WordPress files
      command: cp -a /tmp/wordpress/. /var/www/book.example.com
      args:
        creates: /var/www/book.example.com/wp-settings.php

    - name: Create WordPress MySQL database
      mysql_db:
        name: wordpress
        state: present

    - name: Create WordPress MySQL user
      mysql_user:
        name: wordpress
        host: localhost
        password: bananas
        priv: wordpress.*:ALL

    - name: Create wp-config
      template:
        src: templates/wordpress/wp-config.php
        dest: /var/www/book.example.com/wp-config.php

  #  - name: create backup MySQL
  #    command: mysqldump wordpress > /tmp/wp-database.sql

    - name: Does the database exist?
      command: mysql -u root wordpress -e "SELECT ID FROM wordpress.wp_users LIMIT 1;"
      register: db_exist
      ignore_errors: true

    - name: Copy WordPress DB
      copy:
        src: files/wp-database.sql
        dest: /tmp/wp-database.sql
      when: db_exist.rc > 0

    - name: Import WordPress DB
      mysql_db:
        target: /tmp/wp-database.sql
        state: import
        name: wordpress
      when: db_exist.rc > 0
